### ISSUE TITLE
The ebook contents don't appear in iOS 10

### ISSUE THREAD

**Issue by viniciostorres** [viking2917/angular-epub-reader#1] opened 2019-03-15 19:29 UTC
Hello, Mark

Thanks for sharing your excellent job!

I have tried to test your epub reader but I'm facing a trouble with iOS 10. It does not show the content of ebook. The icon of sidebar works fine, but content does not appear, the area remains white. I tested the app in Android and it works fine.

I'm testing inside an Ionic app:

```
<ion-view cache-view="false">
    <ion-content class="has-header" overflow-scroll="true">
        <epubreader></epubreader>
    </ion-content>
</ion-view>
```

Do you have an idea about it?

**Comment by viking2917** [comment] 2019-03-15 20:06
First let me suggest you use my other repo https://github.com/viking2917/ionic-epub-reader - instead of the angular one. That one is already integrated with Ionic v1, and may clear up your problem. 

I haven't actually tried on iOS 10, I did all my work on 12 (and 11) ... could you download a simulator for version 12 in xCode and see if that works?

**Comment by viking2917** [comment] 2019-03-15 22:05
@viniciostorres I found it. Thank you so much for reporting it. 

The problem was that I was calling 
```window.Keyboard.hideKeyboardAccessoryBar(true); ```

which is now obsolete from the Keyboard plugin, instead of 

```cordova.plugins.Keyboard.hideFormAccessoryBar(true);```

I've committed that change to both the Angular and Ionic variant repos, and I've tested the Ionic version on both iOS 12 and 10 in simulators and it is now working for me. 

If you'll confirm it works for you I'll close this.

**Comment by viniciostorres** [comment] 2019-03-16 02:31
HI, Mark

Thanks for your quick response!

I wasn't clear enough. I copied the directive, style, and template files into my project and I created the page with the code I showed above.

On Android everything works fine:

![Capture+_2019-03-15-23-14-22](https://user-images.githubusercontent.com/1395631/54469660-c9934e80-4779-11e9-978a-b4ad5b0e60c0.png)



 but on device with iOS 10 the page looks like this:

![IMG_0328](https://user-images.githubusercontent.com/1395631/54469670-e0d23c00-4779-11e9-8fd5-2c445c28dc84.PNG)

Thanks a lot for your attention!

**Comment by viniciostorres** [comment] 2019-03-16 03:14
iPhone-X, 12.1 simulator has the same behavior.

**Comment by viking2917** [comment] 2019-03-18 19:08
@viniciostorres got it. Not sure if you saw my above comment about window.Keyboard.hideKeyboardAccessoryBar(true); 
but that is the issue. If you take the current version of the code it should work, I reproduced your issue, and it is corrected with the change I mentioned above...let me know if that works!

**Comment by viniciostorres** [comment] 2019-03-19 02:25
Oh, yes! Today I saw the difference and I fixed this code. Now the behaviour is more "consistent".
I updated the code with your new version of Ionic-epub-reader, updated version of plugins. The content of ebook is loaded, the index and the cover appears in the right tab. But the iframe remains with width and height = 0 and visible attribute = false.

I tested on iPhone with iOS 10 and emulator iOS 12 and the both behaviour is the same.

![Captura de Tela 2019-03-18 às 23 11 09](https://user-images.githubusercontent.com/1395631/54575878-b3cd9580-49d4-11e9-9069-f9d260eb00f8.png)
![Captura de Tela 2019-03-18 às 23 23 28](https://user-images.githubusercontent.com/1395631/54575961-0d35c480-49d5-11e9-8c99-7cf5f35af5b8.png)



I think there is a difference in the structure between your project and mine. But I can't find it.

My project is running ok on Android and on website.

Anyway, thanks for your precious attention. I will follow searching the solution.

**Comment by viking2917** [comment] 2019-03-19 03:44
OK good luck with it. Let me know when you figure it out. 

One other random thought. The Whitelist plugin controls from what domains http requests can be downloaded. I wonder if the whitelister is blocking the download of the ePub file. Do you have the 
``` <allow-navigation href="*" />``` 
set in your config.xml? (I also have 
``` <access origin="*" />``` 
in my config.xml but I can't remember why :)

The bottom of the screen where it says "loading location" is usually seen before the epub gets fully loaded....and stays there if the file doesn't load, is why I ask. You might try using the inspector in Safari with the app attached and see if there are any failures, especially network access denied type failures...

**Comment by viniciostorres** [comment] 2019-03-19 15:43
Wow!! `<allow-navigation href="*" />` opens the door!

After that I just had to adjust Content-Security-Policy to:

```
<meta http-equiv="Content-Security-Policy"
		content="default-src gap://ready file://* blob: *; style-src 'self' blob: http://* https://* 'unsafe-inline'; script-src 'self' http://* https://* 'unsafe-inline' 'unsafe-eval'">
```

I've never had to change these settings before. As Android was not needed I could not see the need for them.

Again: Thank you very much for your help.

**Comment by viking2917** [comment] 2019-03-19 22:21
sweet! Glad it's working. have fun with it. 

I updated the Readme to include a mention of this.

**Closed as completed by viking2917** 2019-03-19 22:21 UTC
